import {describe,it,expect} from 'vitest';
import {approvalTransition,nextRunStatus,routeMessage} from '../domain/crew';
import {orchestrate} from '../domain/orchestrator';
import {newConversation,initialState,resolveApproval} from '../domain/store';
import {ChatProvider} from '../domain/provider';
const provider:ChatProvider={complete:async({agent,context})=>({result:`${agent}:${context}`,evidence:['evidence'],uncertainties:['unknown'],proposedNextAction:'continue'})};

describe('routing and lifecycle',()=>{it('honors explicit mentions and keywords',()=>{expect(routeMessage('Ask @reef and @wake to check this')).toEqual(['reef','wake']);expect(routeMessage('find sources for this')).toEqual(['reef']);});it('enforces lifecycle transitions',()=>{expect(nextRunStatus('queued','start')).toBe('working');expect(nextRunStatus('working','handoff')).toBe('handing_off');expect(nextRunStatus('handing_off','complete')).toBe('completed');expect(nextRunStatus('working','fail')).toBe('failed');});});
describe('orchestration',()=>{it('propagates structured handoff context and preserves fields',async()=>{const result=await orchestrate({conversation:newConversation(),prompt:'research',agents:['reef','wake'],provider});expect(result.conversation.handoffs[0].context).toContain('reef');expect(result.conversation.messages[0].evidence).toEqual(['evidence']);expect(result.conversation.messages.some(message=>message.content.startsWith('Final synthesis:'))).toBe(true);});it('pauses on approval with linked action payload',async()=>{const result=await orchestrate({conversation:newConversation(),prompt:'publish this',agents:['tide'],provider:{...provider,complete:async()=>({result:'draft',evidence:[],uncertainties:[],proposedNextAction:'Publish draft',requiresApproval:true})}});const approval=result.conversation.approvals[0];expect(result.paused).toBe(true);expect(approval.runId).toBe(result.conversation.runs[0].id);expect(JSON.parse(approval.payload).agent).toBe('tide');expect(result.conversation.runs[0].status).toBe('waiting_for_approval');});it('recovers provider failure and records failed run',async()=>{const result=await orchestrate({conversation:newConversation(),prompt:'fail',agents:['reef'],provider:{complete:async()=>{throw new Error('offline')}}});expect(result.conversation.runs[0].status).toBe('failed');expect(result.conversation.runs[0].error).toBe('offline');});it('cancels without leaving a working run',async()=>{const controller=new AbortController();controller.abort();const result=await orchestrate({conversation:newConversation(),prompt:'cancel',agents:['reef'],provider,signal:controller.signal});expect(result.conversation.runs[0].status).toBe('cancelled');});});
describe('approval boundary',()=>{it('approves pending actions but does not mutate decided actions',()=>{const p={id:'1',runId:'r',action:'Publish draft',payload:'{}',status:'pending' as const,createdAt:0};expect(approvalTransition(p,'approve').status).toBe('approved');expect(approvalTransition({...p,status:'denied'},'approve').status).toBe('denied');});});
describe('conversation workspace',()=>{it('starts with a collection and preserves independent histories',()=>{const state=initialState();const second=newConversation('Second task');expect(state.conversations).toHaveLength(1);expect(second.id).not.toBe(state.activeConversationId);expect(second.messages).toEqual([]);});it('resolves an approval and its linked run',()=>{const conversation=newConversation();const result={...conversation,runs:[{id:'run-1',agent:'tide' as const,status:'waiting_for_approval' as const,task:'publish',createdAt:0}],approvals:[{id:'approval-1',runId:'run-1',action:'Publish',payload:'{}',status:'pending' as const,createdAt:0}]};const resolved=resolveApproval(result,'approval-1','approve');expect(resolved.approvals[0].status).toBe('approved');expect(resolved.runs[0].status).toBe('completed');});});
