import {AgentId,agentById,nextRunStatus} from './crew';
import {ChatProvider,ProviderResult} from './provider';
import {Conversation,Event,Handoff,Message,Run} from './store';
export interface OrchestrationOptions{conversation:Conversation;prompt:string;agents:AgentId[];provider:ChatProvider;signal?:AbortSignal;now?:()=>number;uid?:()=>string;}
export interface OrchestrationResult{conversation:Conversation;paused:boolean;}
const event=(id:string,type:string,text:string,createdAt:number):Event=>({id,type,text,createdAt});
export async function orchestrate({conversation,prompt,agents,provider,signal,now=Date.now,uid=()=>crypto.randomUUID()}:OrchestrationOptions):Promise<OrchestrationResult>{let current=conversation;let previous:AgentId='breakwater';let context='';for(const agent of agents){const run:Run={id:uid(),agent,status:nextRunStatus('queued','start'),task:prompt,createdAt:now()};if(signal?.aborted){current={...current,runs:[...current.runs,{...run,status:'cancelled',finishedAt:now(),error:'Run cancelled'}],events:[...current.events,event(uid(),'cancelled',`${agentById(agent).name} was cancelled`,now())]};return{conversation:current,paused:false};}current={...current,runs:[...current.runs,run],events:[...current.events,event(uid(),'working',`${agentById(agent).name} is working`,now())]};try{const result=await provider.complete({prompt,agent,context});if(signal?.aborted)throw new DOMException('Run cancelled','AbortError');const output:Message={id:uid(),role:'assistant',agent,content:result.result,createdAt:now(),evidence:result.evidence,uncertainties:result.uncertainties,proposedNextAction:result.proposedNextAction};const nextContext=JSON.stringify({agent,result});const handoffs:Handoff[]=agent!==previous?[...current.handoffs,{id:uid(),runId:run.id,from:previous,to:agent,context:nextContext,createdAt:now()}]:current.handoffs;const waiting=Boolean(result.requiresApproval);const approval=waiting?{id:uid(),runId:run.id,action:result.proposedNextAction,payload:JSON.stringify({prompt,agent,result}),status:'pending' as const,createdAt:now()}:undefined;const status=waiting?nextRunStatus(run.status,'approval'):nextRunStatus(run.status,'complete');current={...current,runs:current.runs.map(item=>item.id===run.id?{...item,status,finishedAt:waiting?undefined:now(),output:result.result}:item),messages:[...current.messages,output],handoffs,approvals:approval?[...current.approvals,approval]:current.approvals,events:[...current.events,event(uid(),waiting?'waiting_for_approval':'completed',`${agentById(agent).name} returned a structured result`,now())]};context=nextContext;previous=agent;if(waiting)return{conversation:current,paused:true};}catch(error){if(error instanceof DOMException&&error.name==='AbortError'){current={...current,runs:current.runs.map(item=>item.id===run.id?{...item,status:'cancelled',finishedAt:now(),error:error.message}:item),events:[...current.events,event(uid(),'cancelled',`${agentById(agent).name} was cancelled`,now())]};return{conversation:current,paused:false};}const message=error instanceof Error?error.message:String(error);current={...current,runs:current.runs.map(item=>item.id===run.id?{...item,status:'failed',finishedAt:now(),error:message}:item),events:[...current.events,event(uid(),'failed',`${agentById(agent).name} failed: ${message}`,now())]};return{conversation:current,paused:false};}}
if(!signal?.aborted&&agents.length){try{const synthesis=await provider.complete({prompt:`Synthesize the completed specialist work for: ${prompt}`,agent:'breakwater',context});current={...current,messages:[...current.messages,{id:uid(),role:'assistant',agent:'breakwater',content:`Final synthesis: ${synthesis.result}`,createdAt:now(),evidence:synthesis.evidence,uncertainties:synthesis.uncertainties,proposedNextAction:synthesis.proposedNextAction}],events:[...current.events,event(uid(),'completed','Breakwater completed the final synthesis',now())]};}catch(error){current={...current,events:[...current.events,event(uid(),'failed',`Breakwater synthesis failed: ${error instanceof Error?error.message:String(error)}`,now())]};}}
return{conversation:current,paused:false};}
